### PR TITLE
Black formatting

### PR DESCRIPTION
**Pull request by bluegenes**
- [x] reformatted all `.py` files with [black](https://black.readthedocs.io/en/stable/)
 - [x] updated `CONTRIBUTING.md` with black formatting instructions
 - [x] updated `linting.yml` github action to use black

Anything else that needs to go into this PR @olgabot?

### CODE REVIEW

**Comment by pranathivemuri** [comment]
I don't think it needs to be added as a requirement. if it is being added, we can add it to the requirements.txt. I don't see the usefulness of having black as one and the only requirement is a file called dev.txt.

although if we have a PR template like nf-core we could have a line where we say format with black and give the command as nf-core linting does. that might help people lint their own code.

**Comment by pranathivemuri** [comment]
@bluegenes what is the advantage of black over flake8 in one line please?

**Comment by bluegenes** [comment]
`black` reformats code for you, flake does not (afaik).

**Comment by pranathivemuri** [comment]
@olgabot could we merge this?

**Pull request merged**
